version: "3.8"

services:
  db:
    image: postgres:14.1
    container_name: bank-db
    environment:
      POSTGRES_USER: youruser
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: bankdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U youruser -d bankdb"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: bank-app
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bankdb
      - SPRING_DATASOURCE_USERNAME=youruser
      - SPRING_DATASOURCE_PASSWORD=yourpassword
      - SPRING_FLYWAY_URL=jdbc:postgresql://db:5432/bankdb
      - APPLICATION_SECURITY_JWT_SECRET_KEY=Yoursecretkeythatisverylongandsecureandnotthedefaultonefrompropertiesfile

volumes:
  postgres_data:
